### ISSUE TITLE
Add support for importing version comments

### ISSUE THREAD

**Issue by marsv024** [pmonks/alfresco-bulk-import#43]
Importing version comments would be a good feature to have when migrating data from other data sources which do have version control.

I've made a patch for the 1.x version which needs porting to 2.x. See: https://github.com/pmonks/alfresco-bulk-filesystem-import/pull/158

**Comment by pmonks** [comment]
Thanks @marsv024 - any chance you could port your fix to v2.0 and submit a PR?  That would be awesome!

**Comment by pmonks** [comment]
Verified.
