### ISSUE TITLE
Issue importing files in linux where the filenames contain portuguese characters

### ISSUE THREAD

**Issue by jportill13** [pmonks/alfresco-bulk-import#51]
This has only been reproduced in a linux environment with the attached dataset. To reproduce the issue install an alfresco 5 instance and apply the latest bulk import tool amp and follow the steps below:

* Unzip the provided tar in the target server in a directory of your choice, take note of this directory including the directory tony/ this contains the files for the test.
* Login to alfresco as admin and create a folder for the import test
* Open the bulk import tool interface (http://localhost:8080/alfresco/s/bulk/import)
* Enter the location of the "tony" folder (ie /home/alfowner/testdirs/tony)
* Enter the location of the folder in the repo (ie /mytest1)

In the alfresco logs there are warnings about files being unreadable

WARN  [source.fs.DirectoryAnalyser] [BulkImport-Scanner] BULKIMPORT: Skipping '/home/alfowner/testdirs/tony/135 Carbon���13 NMR spectroscopy_DS_NS_final_cau2.txt' as Alfresco does not have permission to read it.

Even though the permissions are right on the server side I believe the issue is with the File.canRead() method. In my tests I found that using java.nio.file.DirectoryStream and java.nio.file.Files.isReadable() is able to read these files properly.

public static void main(String[] args) throws IOException {
		System.out.println("Folder provided was:" + args[0]);
		List<File> originalListing = null;
		File folder = new File(args[0]);
		File[] listOfFiles = folder.listFiles();
		
        int fileNotFoundNew = 0;
        DirectoryStream<Path> ds = Files.newDirectoryStream(folder.toPath());
        for(Iterator<Path> it = ds.iterator();it.hasNext();) {
            Path p = it.next();
            if (!Files.isReadable(p)) {
                fileNotFoundNew++;
                System.out.println("File not readable: " + p);
            } else {
                System.out.println("Read file:     " + p);
            }
        }
	}

[testdirsforbi.tar.gz](https://github.com/pmonks/alfresco-bulk-import/files/56162/testdirsforbi.tar.gz)

**Comment by pmonks** [comment]
Can you check the first item in [this troubleshooting tip](https://github.com/pmonks/alfresco-bulk-import/wiki/Troubleshooting#commonly-seen-symptoms)?  The symptoms sound similar.

**Comment by jportill13** [comment]
Hi Peter,

Thank you for the pointer. After looking at that resolution I changed my LANG variable to LANG=en_US.ISO-8859-1 now my files are no longer being marked as unreadable.

Thank you again.
