### ISSUE TITLE
Add ability to set the content URL in the metadata properties file

### ISSUE THREAD

**Issue by rmknightstar** [pmonks/alfresco-bulk-import#52]
This would be useful in some instances where the files are coming from another repository where the internal folder structure does not match the repository folder structure (e.g. migrating from another alfresco repository).  This would make it possible to just move the content store files over without re-arranging them

**Comment by pmonks** [comment]
Have you looked at the BulkImportSoirce abstraction?  That would be a better way to handle this case.

**Comment by rmknightstar** [comment]
Thanks for the tip -- (it is all coming back to me) :)

**Comment by pmonks** [comment]
[AbstractBulkImportSource](https://github.com/pmonks/alfresco-bulk-import/blob/master/api/src/main/java/org/alfresco/extension/bulkimport/source/AbstractBulkImportSource.java) is worth looking at too.  It simplifies some of the legwork of implementing a custom bulk import source.
