### ISSUE TITLE
Understanding the directory structure

### ISSUE THREAD

**Issue by icybergenome** [pmonks/alfresco-bulk-import#54]
Hey Peters!
I managed to successfully import this project in eclipse but it then further divided in 4 separate projects:

1. alfresco-bulk-import
2. alfresco-bulk-import-api
3. alfresco-bulk-import-parent
4. alfresco-bulk-import-source  

Basically I want to change into some UI and procedure like: 

1. showing the progress of files uploading
2. showing the files failed during operation

It would be great if I understand which project(s) I need to play with. Also after code editing, the build order in which I would get a right .amp and .war files. Also the goals that I need to assign each project.

Thanks in advance.

**Comment by pmonks** [comment]
The [mailing list](https://groups.google.com/forum/#!forum/alfresco-bulk-filesystem-import) would be a better place for this discussion - would you mind reposting there?  Thanks!
