### ISSUE TITLE
Created date not changed

### ISSUE THREAD

**Issue by billydekid** [pmonks/alfresco-bulk-import#69]
I already set my cm:created entry with specific date or NOW but the data ia still displayed as date of file created in system (not Alfresco). 

I use version 2.1.0 and Alfresco 5.1.f.
Is there any configuration I missed?

Thank you.

**Comment by zhihailiu** [comment]
This looks like a dup of https://github.com/pmonks/alfresco-bulk-import/issues/66.

**Comment by pmonks** [comment]
Yep this is definitely a dupe.  I'll try to find the time to push out a binary release that includes the fix.
