### ISSUE TITLE
Unreadable entries due to special character

### ISSUE THREAD

**Issue by zhihailiu** [pmonks/alfresco-bulk-import#71]
### Steps to Reproduce:
 1. Prepare two files in file system with the following names
Caféteria.pdf
Caféteria.pdf.metadata.properties.xml
 2. Run bulk import, check "Dry run"

### Expected Result:
Dry run is successful

### Actual Result:
Dry run result shows - Unreadable entries: 4
Alfresco log shows - Skipping [file name] as Alfresco does not have permission to read it. 

I checked permissions of the files in the file system. Everyone has read permission. As a test, I renamed the files as below to get rid of the special character in names. Dry run didn't have "Unreadable entries" anymore.
Cafeteria.pdf
Cafeteria.pdf.metadata.properties.xml

### Environment:
RHEL, MySQL, Tomcat, JDK1.8, Alfresco 5.0 enterprise

**Comment by pmonks** [comment]
@zhihailiu have you looked at the [Commonly Seen Symptoms](https://github.com/pmonks/alfresco-bulk-import/wiki/Troubleshooting#commonly-seen-symptoms) section of the [Troubleshooting page](https://github.com/pmonks/alfresco-bulk-import/wiki/Troubleshooting) on the wiki?

This looks like the first item in the bulleted list.

**Comment by zhihailiu** [comment]
Peter, sorry I overlooked the troubleshooting page. Worked like a charm. Thank you!
