### ISSUE TITLE
map drive folder as Source directory

### ISSUE THREAD

**Issue by suneethababu** [pmonks/alfresco-bulk-import#72]
Hi, 

    We want to use in-place bulk import, the content store is on map drive E. When I specify the any folder on the map drive as source directory, the error "Source directory not exits" occurred from filesystemBulkImportSource class.

However the import ( streaming) worked with source folder from D drive, Alfreco app server Tomcat is on drive D.

I tried a java program to access the same folder on E and it is finding the folder.

Could you please advice on how can we use the source folder from map drive with bulk import.

**Comment by pmonks** [comment]
G'day @suneethababu - it would be great if you could post this on the [mailing list](https://groups.google.com/forum/#!forum/alfresco-bulk-filesystem-import).  Thanks!
