### ISSUE TITLE
Hang up and failed loads but files and shado files are OK

### ISSUE THREAD

**Issue by jorgegz** [pmonks/alfresco-bulk-import#73]
[RPPF001-Corrida01Fail.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591696/RPPF001-Corrida01Fail.pdf)
[RPPF001-Corrida02Fail.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591697/RPPF001-Corrida02Fail.pdf)
[RPPF001-Corrida03Fail.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591698/RPPF001-Corrida03Fail.pdf)
[RPPF001-Corrida04Fail.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591699/RPPF001-Corrida04Fail.pdf)
[RPPF001-Corrida05Fail.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591700/RPPF001-Corrida05Fail.pdf)
[RPPF001-DryRun.pdf](https://github.com/pmonks/alfresco-bulk-import/files/1591701/RPPF001-DryRun.pdf)

### Steps to Reproduce:
1. Made a Dry Run and was Succesful
2. Made the same load without DryRun and Hang Up once it scan and load about 500 nodes.
3. Verified the file indicated on error log. Nothing strange.
4. Removed the entire directory in which the file was.
5. Made the load again and Hang Up again with a diferent error log.
6. Reduce the size of the load and run again. Finally I get a result Failed.

### Expected Result:
I used to get succesful loads i'm not sure what is the problema because it changes between run and run.

### Actual Result:
Hang ups and fails with diferent error logs

### Environment:
...your operating system, database, app server, JVM version, Alfresco edition and version, etc....
Windows Server 2016 Standard
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

I'm using the default installation of Alfresco so I'm using the included JVM, Tomcat and Alfresco 5.2

**Comment by jorgegz** [comment]
Alfresco Share v5.2.2
(r3fe80908c435c95a09095c64a075aad72adc1714-b41, Aikau 1.0.101.10, Spring Surf 5.2.2, Spring WebScripts 6.15, Freemarker 2.3.20-alfresco-patched, Rhino 1.7R4-alfresco-patched, Yui 2.9.0-alfresco-20141223)
Alfresco Enterprise v5.2.2
(r73ead3c7-b41) schema 10057

**Comment by pmonks** [comment]
The tool has only been tested up to Alfresco v5.1.  Assistance with testing on Alfresco v5.2 welcome!

**Comment by pmonks** [comment]
I took a look at the exceptions and while 1 through 4 aren't useful (those exceptions are a symptom of some other error that's causing the thread pool to shut down), the 5th looks suspicious:

```java.lang.NumberFormatException: For input string: ".3658"```

This exception suggests that you have an error in one of your metadata files, for a file named `EXPEDIENTE_INDAABIN_INDARP00003583_34.pdf`.  It appears as though the metadata file for that file has a decimal value (".3658") for an integer property, and Alfresco is (correctly) reporting that it is unable to make that conversion.

Can you confirm that this is indeed the problem?

The reason that this isn't caught by the dry run is that data type conversion isn't attempted during a dry run - there's no easy way to get Alfresco to perform data type conversions without also having it write to the repository (which obviously defeats the purpose of a dry run feature!).  Regardless of Alfresco's limitations in this area, dry run should attempt data conversions of all properties to catch this kind of thing, and a separate enhancement request on this would be welcome.

**Comment by jorgegz** [comment]
Hi Peter.

Sorry for the Delay. You're right some files had errors and we started to review and update the data in order to complete loads.

Another good news is that a couple days after the installation and configuration of Alfresco the loads run Succesful. So it looks like that at the beginnig something was interfiering and then everything Works fine.

Peter. I'm trying to install Bulk Import on a new instance of Alfresco but I'm getting a message that the amp cannot be applied. ¿Is there a way to avoid this restriction in order to test the 2.1 BI amp on a newer Afresco versión?

![photo_2018-01-17_13-51-02](https://user-images.githubusercontent.com/34919380/35064420-a00f5eaa-fb8f-11e7-8caa-7964d5e9a6e6.jpg)

**Comment by pmonks** [comment]
Looks like you're trying to install the import tool on Alfresco v6.0.  Because it's only been tested on versions up to v5.1, it restricts itself to versions 5.x (as you can see [here](https://github.com/pmonks/alfresco-bulk-import/blob/master/amp/src/main/amp/module.properties#L6)).

If you have access to a test instance of Alfresco, and make sure you backup your alfresco.war file before doing anything else, you could crack open the AMP and change the value of `module.repo.version.max` to `6.99.99` to get past this particular error.  There's no guarantee the tool will work on v6.0, but I'd certainly welcome your help in testing it on that version!
