### ISSUE TITLE
Doesn't see the tool's initiation UI on Alfresco Community (Build: 201707)

### ISSUE THREAD

**Issue by yussenn** [pmonks/alfresco-bulk-import#74]
I doesn't see the tool's initiation UI on Alfresco Community (Build: 201707).  When access to http://127.0.0.1:8080/alfresco/s/bulk/import only get

`
Web Script Status 404 - Not Found
The Web Script /alfresco/s/bulk/import has responded with a status of 404 - Not Found.
404 Description: | Requested resource is not available.

Message:	01060019 Script url /bulk/import does not map to a Web Script.
Server:	Community v5.2.0 (re21f2be5-b22) schema 10.057
Time:	06-feb-2018 13:39:25
`

**Comment by pmonks** [comment]
That means the AMP file wasn't installed correctly.  Take a look at the [installation docs](https://github.com/pmonks/alfresco-bulk-import/wiki/Installation) and if you still have issues please post to the [mailing list](https://groups.google.com/forum/#!forum/alfresco-bulk-filesystem-import).
