### ISSUE TITLE
Message: 09070004 Script url /bulk/import does not map to a Web Script.

### ISSUE THREAD

**Issue by JoaquimOC** [pmonks/alfresco-bulk-import#80]
I have installed AMP, I suppose,  fine installed, because "list" commands show me this:

_Module 'org.alfresco.extension.alfresco-bulk-import' installed in '/opt/alfresco-community/tomcat/webapps/alfresco.war'
   -    Title:        Alfresco Bulk Import v2.1.0 (for Alfresco v5.0+)
   -    Version:      2.1.0
   -    Install Date: Sun Oct 07 19:40:12 CEST 2018
   -    Description:   Alfresco Bulk Import tool. Provides high performance bulk loading of content into Alfresco._

but when I try to run,does not  work:

_The Web Script /alfresco/s/bulk/import has responded with a status of 404 - Not Found.
404 Description: | Requested resource is not available.
Message: 09070004 Script url /bulk/import does not map to a Web Script._

Please, can anyone help me?... I'm new alfresco user

**Comment by pmonks** [comment]
@JoaquimOC questions like this should be posted to the [mailing list](https://groups.google.com/forum/#!forum/alfresco-bulk-filesystem-import), rather than raised as issues.  Thanks!
